// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Enum.proto</summary>
public static partial class EnumReflection {

  #region Descriptor
  /// <summary>File descriptor for Enum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EnumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpFbnVtLnByb3RvKigKDENvc3RJdGVtVHlwZRILCgdDb25zdW1lEAASCwoH",
          "QmV0d2VlbhABKiMKCEl0ZW1UeXBlEgwKCFJlc291cmNlEAASCQoFU3BlZWQQ",
          "AipECgpPYmplY3RUeXBlEgoKBlBsYXllchAAEggKBEhlcm8QARIICgRDYXJk",
          "EAISCAoESXRlbRADEgwKCENvc3RJdGVtEAQqJQoJVGFza1N0YXRlEgoKBkFj",
          "Y2VwdBAAEgwKCEZpbmlzaGVkEAEqMAoGVUlUeXBlEgoKBlVJSGVybxAAEg4K",
          "ClVJQnVpbGRpbmcQARIKCgZVSUNoYXQQAmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CostItemType), typeof(global::ItemType), typeof(global::ObjectType), typeof(global::TaskState), typeof(global::UIType), }, null, null));
  }
  #endregion

}
#region Enums
public enum CostItemType {
  [pbr::OriginalName("Consume")] Consume = 0,
  [pbr::OriginalName("Between")] Between = 1,
}

public enum ItemType {
  [pbr::OriginalName("Resource")] Resource = 0,
  [pbr::OriginalName("Speed")] Speed = 2,
}

public enum ObjectType {
  [pbr::OriginalName("Player")] Player = 0,
  [pbr::OriginalName("Hero")] Hero = 1,
  [pbr::OriginalName("Card")] Card = 2,
  [pbr::OriginalName("Item")] Item = 3,
  [pbr::OriginalName("CostItem")] CostItem = 4,
}

public enum TaskState {
  [pbr::OriginalName("Accept")] Accept = 0,
  [pbr::OriginalName("Finished")] Finished = 1,
}

public enum UIType {
  [pbr::OriginalName("UIHero")] Uihero = 0,
  [pbr::OriginalName("UIBuilding")] Uibuilding = 1,
  [pbr::OriginalName("UIChat")] Uichat = 2,
}

#endregion


#endregion Designer generated code
