// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ObjectMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ObjectMsg.proto</summary>
public static partial class ObjectMsgReflection {

  #region Descriptor
  /// <summary>File descriptor for ObjectMsg.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ObjectMsgReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9PYmplY3RNc2cucHJvdG8aCkVudW0ucHJvdG8aDUNvc3RNc2cucHJvdG8i",
          "zQEKB0hlcm9Nc2cSCgoCSWQYASABKA0SCwoDRXhwGAIgASgFEgwKBE5hbWUY",
          "AyABKAkSGAoGVXBDb3N0GAQgASgLMgguQ29zdE1zZxIZCgdVcENvc3RzGAUg",
          "AygLMgguQ29zdE1zZxIqCglVcENvc3REaWMYBiADKAsyFy5IZXJvTXNnLlVw",
          "Q29zdERpY0VudHJ5GjoKDlVwQ29zdERpY0VudHJ5EgsKA2tleRgBIAEoCRIX",
          "CgV2YWx1ZRgCIAEoCzIILkNvc3RNc2c6AjgBIsQCCglQbGF5ZXJNc2cSCgoC",
          "SWQYASABKA0SCwoDRXhwGAIgASgFEiYKBkhlcm9lcxgDIAMoCzIWLlBsYXll",
          "ck1zZy5IZXJvZXNFbnRyeRIMCgRHb2xkGAQgASgFEhcKBUl0ZW1zGAUgAygL",
          "MgguSGVyb01zZxIQCghJdGVtc0ludBgGIAMoBRIyCgxIZXJvZXNEaWNJbnQY",
          "ByADKAsyHC5QbGF5ZXJNc2cuSGVyb2VzRGljSW50RW50cnkSGwoISXRlbVR5",
          "cGUYCCABKA4yCS5JdGVtVHlwZRo3CgtIZXJvZXNFbnRyeRILCgNrZXkYASAB",
          "KAUSFwoFdmFsdWUYAiABKAsyCC5IZXJvTXNnOgI4ARozChFIZXJvZXNEaWNJ",
          "bnRFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAU6AjgBYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::EnumReflection.Descriptor, global::CostMsgReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HeroMsg), global::HeroMsg.Parser, new[]{ "Id", "Exp", "Name", "UpCost", "UpCosts", "UpCostDic" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerMsg), global::PlayerMsg.Parser, new[]{ "Id", "Exp", "Heroes", "Gold", "Items", "ItemsInt", "HeroesDicInt", "ItemType" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class HeroMsg : pb::IMessage<HeroMsg>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<HeroMsg> _parser = new pb::MessageParser<HeroMsg>(() => new HeroMsg());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<HeroMsg> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ObjectMsgReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HeroMsg() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HeroMsg(HeroMsg other) : this() {
    id_ = other.id_;
    exp_ = other.exp_;
    name_ = other.name_;
    upCost_ = other.upCost_ != null ? other.upCost_.Clone() : null;
    upCosts_ = other.upCosts_.Clone();
    upCostDic_ = other.upCostDic_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HeroMsg Clone() {
    return new HeroMsg(this);
  }

  /// <summary>Field number for the "Id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "Exp" field.</summary>
  public const int ExpFieldNumber = 2;
  private int exp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Exp {
    get { return exp_; }
    set {
      exp_ = value;
    }
  }

  /// <summary>Field number for the "Name" field.</summary>
  public const int NameFieldNumber = 3;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "UpCost" field.</summary>
  public const int UpCostFieldNumber = 4;
  private global::CostMsg upCost_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CostMsg UpCost {
    get { return upCost_; }
    set {
      upCost_ = value;
    }
  }

  /// <summary>Field number for the "UpCosts" field.</summary>
  public const int UpCostsFieldNumber = 5;
  private static readonly pb::FieldCodec<global::CostMsg> _repeated_upCosts_codec
      = pb::FieldCodec.ForMessage(42, global::CostMsg.Parser);
  private readonly pbc::RepeatedField<global::CostMsg> upCosts_ = new pbc::RepeatedField<global::CostMsg>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CostMsg> UpCosts {
    get { return upCosts_; }
  }

  /// <summary>Field number for the "UpCostDic" field.</summary>
  public const int UpCostDicFieldNumber = 6;
  private static readonly pbc::MapField<string, global::CostMsg>.Codec _map_upCostDic_codec
      = new pbc::MapField<string, global::CostMsg>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::CostMsg.Parser), 50);
  private readonly pbc::MapField<string, global::CostMsg> upCostDic_ = new pbc::MapField<string, global::CostMsg>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, global::CostMsg> UpCostDic {
    get { return upCostDic_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as HeroMsg);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(HeroMsg other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Exp != other.Exp) return false;
    if (Name != other.Name) return false;
    if (!object.Equals(UpCost, other.UpCost)) return false;
    if(!upCosts_.Equals(other.upCosts_)) return false;
    if (!UpCostDic.Equals(other.UpCostDic)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Exp != 0) hash ^= Exp.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (upCost_ != null) hash ^= UpCost.GetHashCode();
    hash ^= upCosts_.GetHashCode();
    hash ^= UpCostDic.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Exp != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Exp);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (upCost_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(UpCost);
    }
    upCosts_.WriteTo(output, _repeated_upCosts_codec);
    upCostDic_.WriteTo(output, _map_upCostDic_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Exp != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Exp);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (upCost_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(UpCost);
    }
    upCosts_.WriteTo(ref output, _repeated_upCosts_codec);
    upCostDic_.WriteTo(ref output, _map_upCostDic_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (Exp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (upCost_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpCost);
    }
    size += upCosts_.CalculateSize(_repeated_upCosts_codec);
    size += upCostDic_.CalculateSize(_map_upCostDic_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(HeroMsg other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Exp != 0) {
      Exp = other.Exp;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.upCost_ != null) {
      if (upCost_ == null) {
        UpCost = new global::CostMsg();
      }
      UpCost.MergeFrom(other.UpCost);
    }
    upCosts_.Add(other.upCosts_);
    upCostDic_.MergeFrom(other.upCostDic_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Exp = input.ReadInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          if (upCost_ == null) {
            UpCost = new global::CostMsg();
          }
          input.ReadMessage(UpCost);
          break;
        }
        case 42: {
          upCosts_.AddEntriesFrom(input, _repeated_upCosts_codec);
          break;
        }
        case 50: {
          upCostDic_.AddEntriesFrom(input, _map_upCostDic_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Exp = input.ReadInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          if (upCost_ == null) {
            UpCost = new global::CostMsg();
          }
          input.ReadMessage(UpCost);
          break;
        }
        case 42: {
          upCosts_.AddEntriesFrom(ref input, _repeated_upCosts_codec);
          break;
        }
        case 50: {
          upCostDic_.AddEntriesFrom(ref input, _map_upCostDic_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayerMsg : pb::IMessage<PlayerMsg>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerMsg> _parser = new pb::MessageParser<PlayerMsg>(() => new PlayerMsg());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerMsg> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ObjectMsgReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerMsg() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerMsg(PlayerMsg other) : this() {
    id_ = other.id_;
    exp_ = other.exp_;
    heroes_ = other.heroes_.Clone();
    gold_ = other.gold_;
    items_ = other.items_.Clone();
    itemsInt_ = other.itemsInt_.Clone();
    heroesDicInt_ = other.heroesDicInt_.Clone();
    itemType_ = other.itemType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerMsg Clone() {
    return new PlayerMsg(this);
  }

  /// <summary>Field number for the "Id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "Exp" field.</summary>
  public const int ExpFieldNumber = 2;
  private int exp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Exp {
    get { return exp_; }
    set {
      exp_ = value;
    }
  }

  /// <summary>Field number for the "Heroes" field.</summary>
  public const int HeroesFieldNumber = 3;
  private static readonly pbc::MapField<int, global::HeroMsg>.Codec _map_heroes_codec
      = new pbc::MapField<int, global::HeroMsg>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::HeroMsg.Parser), 26);
  private readonly pbc::MapField<int, global::HeroMsg> heroes_ = new pbc::MapField<int, global::HeroMsg>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<int, global::HeroMsg> Heroes {
    get { return heroes_; }
  }

  /// <summary>Field number for the "Gold" field.</summary>
  public const int GoldFieldNumber = 4;
  private int gold_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gold {
    get { return gold_; }
    set {
      gold_ = value;
    }
  }

  /// <summary>Field number for the "Items" field.</summary>
  public const int ItemsFieldNumber = 5;
  private static readonly pb::FieldCodec<global::HeroMsg> _repeated_items_codec
      = pb::FieldCodec.ForMessage(42, global::HeroMsg.Parser);
  private readonly pbc::RepeatedField<global::HeroMsg> items_ = new pbc::RepeatedField<global::HeroMsg>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HeroMsg> Items {
    get { return items_; }
  }

  /// <summary>Field number for the "ItemsInt" field.</summary>
  public const int ItemsIntFieldNumber = 6;
  private static readonly pb::FieldCodec<int> _repeated_itemsInt_codec
      = pb::FieldCodec.ForInt32(50);
  private readonly pbc::RepeatedField<int> itemsInt_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> ItemsInt {
    get { return itemsInt_; }
  }

  /// <summary>Field number for the "HeroesDicInt" field.</summary>
  public const int HeroesDicIntFieldNumber = 7;
  private static readonly pbc::MapField<int, int>.Codec _map_heroesDicInt_codec
      = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 58);
  private readonly pbc::MapField<int, int> heroesDicInt_ = new pbc::MapField<int, int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<int, int> HeroesDicInt {
    get { return heroesDicInt_; }
  }

  /// <summary>Field number for the "ItemType" field.</summary>
  public const int ItemTypeFieldNumber = 8;
  private global::ItemType itemType_ = global::ItemType.Resource;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ItemType ItemType {
    get { return itemType_; }
    set {
      itemType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerMsg);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerMsg other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Exp != other.Exp) return false;
    if (!Heroes.Equals(other.Heroes)) return false;
    if (Gold != other.Gold) return false;
    if(!items_.Equals(other.items_)) return false;
    if(!itemsInt_.Equals(other.itemsInt_)) return false;
    if (!HeroesDicInt.Equals(other.HeroesDicInt)) return false;
    if (ItemType != other.ItemType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Exp != 0) hash ^= Exp.GetHashCode();
    hash ^= Heroes.GetHashCode();
    if (Gold != 0) hash ^= Gold.GetHashCode();
    hash ^= items_.GetHashCode();
    hash ^= itemsInt_.GetHashCode();
    hash ^= HeroesDicInt.GetHashCode();
    if (ItemType != global::ItemType.Resource) hash ^= ItemType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Exp != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Exp);
    }
    heroes_.WriteTo(output, _map_heroes_codec);
    if (Gold != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gold);
    }
    items_.WriteTo(output, _repeated_items_codec);
    itemsInt_.WriteTo(output, _repeated_itemsInt_codec);
    heroesDicInt_.WriteTo(output, _map_heroesDicInt_codec);
    if (ItemType != global::ItemType.Resource) {
      output.WriteRawTag(64);
      output.WriteEnum((int) ItemType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Exp != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Exp);
    }
    heroes_.WriteTo(ref output, _map_heroes_codec);
    if (Gold != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gold);
    }
    items_.WriteTo(ref output, _repeated_items_codec);
    itemsInt_.WriteTo(ref output, _repeated_itemsInt_codec);
    heroesDicInt_.WriteTo(ref output, _map_heroesDicInt_codec);
    if (ItemType != global::ItemType.Resource) {
      output.WriteRawTag(64);
      output.WriteEnum((int) ItemType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (Exp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
    }
    size += heroes_.CalculateSize(_map_heroes_codec);
    if (Gold != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
    }
    size += items_.CalculateSize(_repeated_items_codec);
    size += itemsInt_.CalculateSize(_repeated_itemsInt_codec);
    size += heroesDicInt_.CalculateSize(_map_heroesDicInt_codec);
    if (ItemType != global::ItemType.Resource) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerMsg other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Exp != 0) {
      Exp = other.Exp;
    }
    heroes_.MergeFrom(other.heroes_);
    if (other.Gold != 0) {
      Gold = other.Gold;
    }
    items_.Add(other.items_);
    itemsInt_.Add(other.itemsInt_);
    heroesDicInt_.MergeFrom(other.heroesDicInt_);
    if (other.ItemType != global::ItemType.Resource) {
      ItemType = other.ItemType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Exp = input.ReadInt32();
          break;
        }
        case 26: {
          heroes_.AddEntriesFrom(input, _map_heroes_codec);
          break;
        }
        case 32: {
          Gold = input.ReadInt32();
          break;
        }
        case 42: {
          items_.AddEntriesFrom(input, _repeated_items_codec);
          break;
        }
        case 50:
        case 48: {
          itemsInt_.AddEntriesFrom(input, _repeated_itemsInt_codec);
          break;
        }
        case 58: {
          heroesDicInt_.AddEntriesFrom(input, _map_heroesDicInt_codec);
          break;
        }
        case 64: {
          ItemType = (global::ItemType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Exp = input.ReadInt32();
          break;
        }
        case 26: {
          heroes_.AddEntriesFrom(ref input, _map_heroes_codec);
          break;
        }
        case 32: {
          Gold = input.ReadInt32();
          break;
        }
        case 42: {
          items_.AddEntriesFrom(ref input, _repeated_items_codec);
          break;
        }
        case 50:
        case 48: {
          itemsInt_.AddEntriesFrom(ref input, _repeated_itemsInt_codec);
          break;
        }
        case 58: {
          heroesDicInt_.AddEntriesFrom(ref input, _map_heroesDicInt_codec);
          break;
        }
        case 64: {
          ItemType = (global::ItemType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
