// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Request.proto</summary>
public static partial class RequestReflection {

  #region Descriptor
  /// <summary>File descriptor for Request.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RequestReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1SZXF1ZXN0LnByb3RvImQKB1JlcXVlc3QSCgoCaWQYASABKAMSCwoDbnVt",
          "GAIgASgDEgwKBGhlcm8YAyABKAkSDwoHaGVyb19pZBghIAEoCRIPCgdoZXJv",
          "SWRkGCIgASgJEhAKCEhlcm9JZGRkGCMgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Id", "Num", "Hero", "HeroId", "HeroIdd", "HeroIddd" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RequestReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request(Request other) : this() {
    id_ = other.id_;
    num_ = other.num_;
    hero_ = other.hero_;
    heroId_ = other.heroId_;
    heroIdd_ = other.heroIdd_;
    heroIddd_ = other.heroIddd_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 2;
  private long num_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Num {
    get { return num_; }
    set {
      num_ = value;
    }
  }

  /// <summary>Field number for the "hero" field.</summary>
  public const int HeroFieldNumber = 3;
  private string hero_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Hero {
    get { return hero_; }
    set {
      hero_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "hero_id" field.</summary>
  public const int HeroIdFieldNumber = 33;
  private string heroId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HeroId {
    get { return heroId_; }
    set {
      heroId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "heroIdd" field.</summary>
  public const int HeroIddFieldNumber = 34;
  private string heroIdd_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HeroIdd {
    get { return heroIdd_; }
    set {
      heroIdd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "HeroIddd" field.</summary>
  public const int HeroIdddFieldNumber = 35;
  private string heroIddd_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HeroIddd {
    get { return heroIddd_; }
    set {
      heroIddd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Num != other.Num) return false;
    if (Hero != other.Hero) return false;
    if (HeroId != other.HeroId) return false;
    if (HeroIdd != other.HeroIdd) return false;
    if (HeroIddd != other.HeroIddd) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Num != 0L) hash ^= Num.GetHashCode();
    if (Hero.Length != 0) hash ^= Hero.GetHashCode();
    if (HeroId.Length != 0) hash ^= HeroId.GetHashCode();
    if (HeroIdd.Length != 0) hash ^= HeroIdd.GetHashCode();
    if (HeroIddd.Length != 0) hash ^= HeroIddd.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Num != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Num);
    }
    if (Hero.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Hero);
    }
    if (HeroId.Length != 0) {
      output.WriteRawTag(138, 2);
      output.WriteString(HeroId);
    }
    if (HeroIdd.Length != 0) {
      output.WriteRawTag(146, 2);
      output.WriteString(HeroIdd);
    }
    if (HeroIddd.Length != 0) {
      output.WriteRawTag(154, 2);
      output.WriteString(HeroIddd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Num != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Num);
    }
    if (Hero.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Hero);
    }
    if (HeroId.Length != 0) {
      output.WriteRawTag(138, 2);
      output.WriteString(HeroId);
    }
    if (HeroIdd.Length != 0) {
      output.WriteRawTag(146, 2);
      output.WriteString(HeroIdd);
    }
    if (HeroIddd.Length != 0) {
      output.WriteRawTag(154, 2);
      output.WriteString(HeroIddd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Num != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Num);
    }
    if (Hero.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Hero);
    }
    if (HeroId.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(HeroId);
    }
    if (HeroIdd.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(HeroIdd);
    }
    if (HeroIddd.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(HeroIddd);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Num != 0L) {
      Num = other.Num;
    }
    if (other.Hero.Length != 0) {
      Hero = other.Hero;
    }
    if (other.HeroId.Length != 0) {
      HeroId = other.HeroId;
    }
    if (other.HeroIdd.Length != 0) {
      HeroIdd = other.HeroIdd;
    }
    if (other.HeroIddd.Length != 0) {
      HeroIddd = other.HeroIddd;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 16: {
          Num = input.ReadInt64();
          break;
        }
        case 26: {
          Hero = input.ReadString();
          break;
        }
        case 266: {
          HeroId = input.ReadString();
          break;
        }
        case 274: {
          HeroIdd = input.ReadString();
          break;
        }
        case 282: {
          HeroIddd = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 16: {
          Num = input.ReadInt64();
          break;
        }
        case 26: {
          Hero = input.ReadString();
          break;
        }
        case 266: {
          HeroId = input.ReadString();
          break;
        }
        case 274: {
          HeroIdd = input.ReadString();
          break;
        }
        case 282: {
          HeroIddd = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
